From aiminy/isseq:1.1


#RUN git config --global --unset http.proxy 
#RUN git config --global --unset https.proxy

#RUN git clone https://github.com/aiminy/IS-Seq-python3.git IsSeq

CMD ["Rscript","/usr/src/IsSeq/R/INSPIIRED/Convert_IsSeq_Script.R"]
