From aiminy/isseq:1.1

#RUN git config --global --unset http.proxy 
#RUN git config --global --unset https.proxy

RUN git clone https://github.com/aiminy/IS-Seq-python3.git IsSeq

RUN R -e "install.packages(c('rtracklayer'),dependencies=TRUE,repos='http://cran.rstudio.com/')"

CMD ["Rscript","/usr/src/IsSeq/R/makeREFIndex1.R"]
